openapi: 3.0.3
info:
  title: Pingu Go API
  version: 1.0.0
  description: API com contrato OpenAPI simples.
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: API ativa
  /users:
    get:
      summary: Lista usuarios
      responses:
        '200':
          description: Usuarios retornados
