'use strict';

const assert = require('assert/strict');
const test = require('node:test');

const { analyzeText } = require('../lib/analyzer');

// Corpus de regressao anti-falso-positivo: cada trecho e codigo LEGITIMO que se
// parece com o gatilho de um detector mas nao deve dispara-lo. Protege contra
// regressoes que tornem as guardas conservadoras frouxas demais. Para cada caso,
// nenhuma issue dos `kinds` proibidos pode aparecer na analise completa.
const CASES = [
  {
    name: 'JS: duas comparacoes ligadas por && nao sao comparacao encadeada',
    file: '/tmp/fp/range.js',
    code: ['function inRange(a, b, c) {', '  return a < b && b < c;', '}', ''].join('\n'),
    forbid: ['chained_comparison'],
  },
  {
    name: 'JS: for await...of e await Promise.all nao sao await_in_loop',
    file: '/tmp/fp/stream.js',
    code: [
      'async function drain(stream, groups) {',
      '  for await (const chunk of stream) {',
      '    handle(chunk);',
      '  }',
      '  for (const group of groups) {',
      '    await Promise.all(group.map(work));',
      '  }',
      '}',
      '',
    ].join('\n'),
    forbid: ['await_in_loop'],
  },
  {
    name: 'JS: atribuicao intencional com parenteses duplos nao e assignment_in_condition',
    file: '/tmp/fp/match.js',
    code: [
      'function scan(re, text) {',
      '  let m;',
      '  while ((m = re.exec(text))) {',
      '    use(m);',
      '  }',
      '}',
      '',
    ].join('\n'),
    forbid: ['assignment_in_condition'],
  },
  {
    name: 'JS: typeof valido, Number.isNaN e parseInt com base nao disparam',
    file: '/tmp/fp/checks.js',
    code: [
      'function classify(x, raw) {',
      '  if (typeof x === "function") {',
      '    return "fn";',
      '  }',
      '  if (Number.isNaN(x)) {',
      '    return "nan";',
      '  }',
      '  return parseInt(raw, 10);',
      '}',
      '',
    ].join('\n'),
    forbid: ['invalid_typeof', 'nan_comparison', 'parseint_no_radix'],
  },
  {
    name: 'Python: comparacao encadeada valida e is None idiomatico',
    file: '/tmp/fp/range.py',
    code: [
      'def check(a, b, c, value):',
      '    if a < b < c:',
      '        return True',
      '    return value is None',
      '',
    ].join('\n'),
    forbid: ['chained_comparison', 'literal_identity_comparison'],
  },
  {
    name: 'Python: variaveis de dominio nao sao shadowing de builtin',
    file: '/tmp/fp/names.py',
    code: [
      'def build(items):',
      '    item_list = list(items)',
      '    config = {}',
      '    total_sum = 0',
      '    return item_list, config, total_sum',
      '',
    ].join('\n'),
    forbid: ['shadowed_builtin'],
  },
  {
    name: 'Python: dunders corretos nao sao typo',
    file: '/tmp/fp/model.py',
    code: [
      'class Money:',
      '    def __init__(self, amount):',
      '        self.amount = amount',
      '',
      '    def __repr__(self):',
      '        return f"Money({self.amount})"',
      '',
      '    def __eq__(self, other):',
      '        return self.amount == other.amount',
      '',
    ].join('\n'),
    forbid: ['dunder_typo'],
  },
  {
    name: 'JS: == null e membro custom parseInt nao disparam',
    file: '/tmp/fp/nullish.js',
    code: [
      'function pick(x, parser) {',
      '  if (x == null) {',
      '    return parser.parseInt(x);',
      '  }',
      '  return x;',
      '}',
      '',
    ].join('\n'),
    forbid: ['loose_equality', 'parseint_no_radix'],
  },
  {
    name: 'JS: comparacao entre chamadas distintas nao e auto-comparacao',
    file: '/tmp/fp/calls.js',
    code: [
      'function changed(read) {',
      '  return read() === read();',
      '}',
      '',
    ].join('\n'),
    forbid: ['self_comparison'],
  },
  {
    name: 'JS: import usado em JSX/codigo nao e import nao utilizado',
    file: '/tmp/fp/use-import.js',
    code: [
      'const { readFile } = require("fs/promises");',
      '',
      'async function load(path) {',
      '  return readFile(path, "utf8");',
      '}',
      '',
      'module.exports = { load };',
      '',
    ].join('\n'),
    forbid: ['unused_import'],
  },
  {
    name: 'JS: binding de catch nao e variavel indefinida',
    file: '/tmp/fp/catch.js',
    code: [
      'function run(task) {',
      '  try {',
      '    return task();',
      '  } catch (error) {',
      '    return String(error && error.message);',
      '  }',
      '}',
      '',
    ].join('\n'),
    forbid: ['undefined_variable'],
  },
  {
    name: 'JS: const de modulo (require) usada em funcao nao e indefinida',
    file: '/tmp/fp/module-const.js',
    code: [
      'const config = require("./config");',
      '',
      'function read(key) {',
      '  return config[key];',
      '}',
      '',
    ].join('\n'),
    forbid: ['undefined_variable'],
  },
  {
    name: 'JS: parametro de funcao aninhada nao e indefinido',
    file: '/tmp/fp/nested.js',
    code: [
      'function outer() {',
      '  function inner(rawResult) {',
      '    return rawResult.value;',
      '  }',
      '  return inner;',
      '}',
      '',
    ].join('\n'),
    forbid: ['undefined_variable'],
  },
  {
    name: 'JS: parametros desestruturados em arrow nao sao indefinidos',
    file: '/tmp/fp/destructure.js',
    code: [
      'function build(entries) {',
      '  return entries.filter(([key, value]) => key && value);',
      '}',
      '',
    ].join('\n'),
    forbid: ['undefined_variable'],
  },
  {
    name: 'JS: conteudo de literal de regex nao vira identificador',
    file: '/tmp/fp/regex.js',
    code: [
      'function detect(text) {',
      '  const isPrisma = /\\bprisma\\b/.test(text);',
      '  return isPrisma;',
      '}',
      '',
    ].join('\n'),
    forbid: ['undefined_variable'],
  },
  {
    name: 'JS: delimitadores dentro de regex nao corrompem a analise de sintaxe',
    file: '/tmp/fp/regex-syntax.js',
    code: [
      'function parse(line) {',
      '  const a = /^\\s*(?:public|private)\\s+([A-Za-z_$][\\w$]*)/.exec(line);',
      '  const b = /\\)\\s*\\.(?:then|catch)\\b/.test(line);',
      '  return /^\\}/.test(line) && a && b;',
      '}',
      '',
    ].join('\n'),
    forbid: ['syntax_missing_comma', 'syntax_extra_delimiter', 'syntax_missing_quote'],
  },
  {
    name: 'JS: chaves de template literal com interpolacao nao sao delimitador extra',
    file: '/tmp/fp/template.js',
    code: [
      'function render(user, items) {',
      '  const head = `<div class="${user.role}">${user.name}</div>`;',
      '  const body = `total: ${items.reduce((sum, it) => sum + it.value, 0)}`;',
      '  return head + body;',
      '}',
      '',
    ].join('\n'),
    forbid: ['syntax_extra_delimiter', 'syntax_missing_comma', 'syntax_missing_quote'],
  },
  {
    name: 'JS: helpers internos (nao exportados) nao exigem documentacao',
    file: '/tmp/fp/internal-helper.js',
    code: [
      'function internalHelper(value) {',
      '  return value * 2;',
      '}',
      '',
      'function anotherHelper(value) {',
      '  return value + 1;',
      '}',
      '',
      'module.exports = { run: () => internalHelper(anotherHelper(1)) };',
      '',
    ].join('\n'),
    forbid: ['function_doc'],
  },
  {
    name: 'Python: funcao privada (_helper) nao exige documentacao',
    file: '/tmp/fp/private.py',
    code: [
      'def _helper(value):',
      '    return value * 2',
      '',
    ].join('\n'),
    forbid: ['function_doc', 'function_comment'],
  },
  {
    name: 'JS: helper interno nao exige comentario de manutencao',
    file: '/tmp/fp/internal-comment.js',
    code: [
      'function internalHelper(value) {',
      '  return value * 2;',
      '}',
      '',
      'module.exports = { run: () => internalHelper(1) };',
      '',
    ].join('\n'),
    forbid: ['function_comment'],
  },
  {
    name: 'Elixir: funcao privada (defp) nao exige comentario de manutencao',
    file: '/tmp/fp/private.ex',
    code: [
      'defp helper(value) do',
      '  value * 2',
      'end',
      '',
    ].join('\n'),
    forbid: ['function_comment'],
  },
  {
    name: 'Go: indentacao com tab e idiomatica (gofmt), nao e problema de higiene',
    file: '/tmp/fp/sample.go',
    code: [
      'package main',
      '',
      'func Total(items []int) int {',
      '\tsum := 0',
      '\tfor _, value := range items {',
      '\t\tsum += value',
      '\t}',
      '\treturn sum',
      '}',
      '',
    ].join('\n'),
    forbid: ['tabs'],
  },
  {
    name: 'Lua: variaveis locais e de loop nao sao indefinidas',
    file: '/tmp/fp/sample.lua',
    code: [
      'local function total(items)',
      '  local subtotal = 0',
      '  for _, item in ipairs(items) do',
      '    subtotal = subtotal + item.price',
      '  end',
      '  return subtotal',
      'end',
      '',
    ].join('\n'),
    forbid: ['undefined_variable', 'syntax_missing_comma', 'syntax_extra_delimiter'],
  },
  {
    name: 'Shell: variaveis locais e de loop nao sao indefinidas',
    file: '/tmp/fp/sample.sh',
    code: [
      '#!/usr/bin/env bash',
      'total() {',
      '  local sum=0',
      '  for value in "$@"; do',
      '    sum=$((sum + value))',
      '  done',
      '  echo "$sum"',
      '}',
      '',
    ].join('\n'),
    forbid: ['undefined_variable', 'syntax_missing_comma', 'syntax_extra_delimiter'],
  },
  {
    name: 'Rust: parametro de closure (|item|) nao e variavel indefinida',
    file: '/tmp/fp/closure.rs',
    code: [
      'pub fn total(items: &[i64]) -> i64 {',
      '    let sum: i64 = items.iter().map(|item| item * 2).sum();',
      '    sum',
      '}',
      '',
    ].join('\n'),
    forbid: ['undefined_variable'],
  },
  {
    name: 'Go: funcao privada (inicial minuscula) nao exige doc/comentario',
    file: '/tmp/fp/private-go.go',
    code: [
      'package main',
      '',
      'func describe(value int) int {',
      '\treturn value * 2',
      '}',
      '',
    ].join('\n'),
    forbid: ['function_doc', 'function_comment'],
  },
  {
    name: 'JS: statements no corpo de funcao dentro de objeto nao pedem virgula',
    file: '/tmp/fp/object-methods.js',
    code: [
      'const handlers = {',
      '  load(path) {',
      '    const result = read(path)',
      '    return result',
      '  },',
      '  save(path, data) {',
      '    const ok = write(path, data)',
      '    return ok',
      '  },',
      '};',
      '',
    ].join('\n'),
    forbid: ['syntax_missing_comma'],
  },
];

for (const testCase of CASES) {
  test(`sem falso positivo — ${testCase.name}`, () => {
    const issues = analyzeText(testCase.file, testCase.code);
    const offending = issues.filter((issue) => testCase.forbid.includes(issue.kind));
    assert.deepEqual(
      offending.map((issue) => `${issue.kind}@${issue.line}`),
      [],
      `nenhum dos kinds ${testCase.forbid.join(', ')} deveria disparar`,
    );
  });
}
